config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root "users/sessions#new"
  end
  #ログイン画面をトップ画面に

  devise_for :users, :controller => {
    sessions: 'users/sessions'
  }

  get '/top'=> 'tasks#index'

  resources :users ,only: [:index, :show, :edit, :update]
  resources :owners do
    collection do
      get 'search' => 'owners#search' #検索窓追加のため
    end
    member do
      get 'material_edit'
      get 'material_create'
      post 'material_create'
      patch 'material_update'
    end
  end

  resources :quotations
  get '/owner/:id/quotations/' => 'quotations#index', as: 'quotations_index'
  get '/owner/:id/quotations/new' => 'quotations#new', as: 'quotation_new'
  #物件の見積もり一覧取得のため

  resources :clients do
    collection do
      get 'search' => 'clients#search'
    end
  end
  #検索窓追加のため

  resources :chats
  resources :rooms, only: %i[create index show]
  resources :materials do
    collection do
      post 'update_all'
    end
  end

  resources :tasks

  get 'unsubscribe/:name' => 'users#unsubscribe', as: 'confirm_unsubscribe' #退会画面へ遷移
  patch '/users/:id/unsubscribe' => 'users#withdraw', as: 'unsubscribe_withdraw_user' #会員ステータス切り替え



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room


end

app/models/client.rb
class Client < ApplicationRecord

    has_many :owners
    #has_many :sales_outlets
    #has_many :construction_shops
    belongs_to :user, optional: true

    def self.search(keyword)
        where(["name like?", "%#{keyword}%"])
    end
end

app/models/construction_shop.rb
class ConstructionShop < ApplicationRecord
  #belongs_to :client
  belongs_to :sales_outlet, optional: true
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :owner, inverse_of: :materials
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :quotations
  belongs_to :client

  has_many :materials, dependent: :destroy, inverse_of: :owner
  accepts_nested_attributes_for :materials, allow_destroy: true #ビューからデータを送る際にownerと一緒にmaterialを送る

  def self.search(keyword)
    where(["name like?", "%#{keyword}%"])
  end
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :owner
  belongs_to :user
  
  mount_uploader :pdf, AvatarUploader
  #has_many_attached :pdfs

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms, dependent: :destroy
  has_many :chats
  has_many :users, through: :user_rooms

  # チャット通知を既読にするためのメゾット
  def check_chats_notification(current_user)
    unchecked_chats = chats.includes(:user).where(checked: false).where.not(user_id: current_user.id)
 # &.を記述することで、uncheked_chatsがnilの場合エラーをNoMethodErrorを出さずにnilを返す。
    unchecked_chats&.each { |unchecked_chat| unchecked_chat.update(checked: true) }
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :quotations
  has_many :clients
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :tasks, dependent: :destroy

  def active_for_authentication?
    super && self.is_deleted?
  end

  def inactive_message
    self.is_deleted? ? super : :special_condition_is_not_valid
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
 before_action :authenticate_user!

 def index
  @users = User.all.page(params[:page]).per(10)
 end

 def show
  @user = User.find(params[:id])
  rooms = current_user.user_rooms.pluck(:room_id)
  user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

  if user_rooms.nil? #チャットroomがない場合新規作成
   @room = Room.new
   @room.save
   UserRoom.create(user_id: @user.id, room_id: @room.id) #チャット相手のroom作成
   UserRoom.create(user_id: current_user.id, room_id: @room.id) #カレントユーザーのroom作成
  else #チャットルームがすでにある場合の分岐
   @room = user_rooms.room
  end

  @chats = @room.chats
  @chat = Chat.new(room_id: @room.id)
 end

 def create
  @chat = current_user.chats.new(chat_params)
  @chat.save! #非同期通信のため、redirect先の記載なし
 end

 private

 def chat_params
  params.require(:chat).permit(:message, :room_id)
 end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
   before_action :authenticate_user!

  def new
    @owner = Owner.new
    @clients = Client.all
    @material = @owner.materials.build #ownerに紐づくmaterial作成
  end

  def index
    @owners = Owner.all.page(params[:page]).per(10) #ページネーション
  end

  def show
    @owner = Owner.find(params[:id])
    @materials = @owner.materials #ownerに紐づくmaterialをすべて呼び出し
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save!
      redirect_to owner_path(@owner)
    else
      redirect_back
    end
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def material_edit #ownerに紐づくmaterial編集アクション
    @owner = Owner.find(params[:id])
  end

  def material_update #ownerに紐づくmaterial更新アクション
    @owner = Owner.find(params[:id])
    if @owner.update(material_params)
      flash[:success] = "情報を更新しました"
      redirect_to owner_path(@owner)
    else
      render 'material_edit'
    end
  end

  def material_create #ownerに紐づくmaterial作成アクション
    @owner = Owner.find(params[:id])
    @material = @owner.materials.build
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy!
    redirect_to owners_path
  end

  def update
    @owner = Owner.find(params[:id])
    if @owner.update(owner_params)
      flash[:success] = "情報を更新しました"
      redirect_to owner_path(@owner)
    else
      render 'edit'
    end
  end

  def search
    @owners = Owner.search(params[:keyword]).page(params[:id]).per(10) #検索結果の画面にもページネーション
    @keyword = params[:keyword]
    render "index" #検索窓
  end

  private
  def owner_params
    params.require(:owner).permit(:client_id, :name, materials_attributes: [:id, :material_name, :order_status, :order_date, :_destroy]) #owner作成時にmaterials_attributesの中身も作成
  end

  def material_params
    params.require(:owner).permit(materials_attributes: [:id, :material_name, :order_status, :order_date, :updated_at, :_destroy]) #owner作成時にmaterials_attributesの中身も作成
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/owners/_material_edit_fields.html.erb
  <div class="form-group">
    <%= f.label :material_name, "資材名", class: "font-weight-bold" %>
      <%= f.text_field :material_name %>
      <%= f.hidden_field :id %>
      <%= f.hidden_field :updated_at %>
  </div>
  <div class="form-group">
    <%= f.label :order_status, "発注状況", class: "font-weight-bold"  %>
    <%= f.radio_button :order_status, true %><%= f.label :order_status, "発注済み", value: true %>
    <%= f.radio_button :order_status, false %><%= f.label :order_status, "未発注", value: false %>
  </div>

  <div class="form-group">
    <%= f.label :order_date, "発注予定日", class: "font-weight-bold"  %>
    <%= f.date_field :order_date %>
  </div>

  <div class="form-group text-right">
      <%= link_to_remove_association "削除", f , class:"btn btn-outline-secondary" %>
  </div>

app/views/owners/_material_fields.html.erb
<div class="row nested-fields">
  <div class="form-group">
    <%= f.label :material_name, "資材名",class: "font-weight-bold" %>
    <%= f.text_field :material_name %>
    <%= f.hidden_field :order_status, value: false %>
    <%= f.hidden_field :order_date %>
    <%= f.hidden_field :id %>
  </div>

  <div class="form-group ml-3">
      <%= link_to_remove_association "削除", f , class:"btn btn-outline-secondary" %>
  </div>
</div>

app/views/owners/_material_new_fields.html.erb
    <%= f.text_field :material_name %>
    <%= f.hidden_field :order_status, value: false %>
    <%= f.hidden_field :order_date %>
    <%= f.hidden_field :id %>

app/views/owners/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2>物件編集</h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="text-center">
    <%= form_with model: @owner, local: true do |f| %>
    <div class="mt-3">
      <%= f.label :name, "物件名" %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.submit "変更", class: "btn btn-outline-secondary" %>
      <%= link_to "削除", owner_path(@owner), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-outline-secondary" %>
    </div>
  <% end %>
  </div>

</div>

app/views/owners/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2>物件一覧</h2>
    </div>
  </div>
</div>

<div class="container">
    <div class="text-right">
      <%= form_with url: search_owners_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索" %>
      <% end %>
    </div>
</div>

<div class="container">
  <div class="text-left mb-1">
    <%= link_to "物件追加", new_owner_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

<div class="container">
  <div class="mx-auto text-center">
    <table class="table table-bordered">
      <thead class="bg-light">
        <tr>
          <th>物件名</th>
          <th>顧客名</th>
        </tr>
      </thead>
      <tbody>
        <% @owners.each do |owner| %>
        <tr>
          <td>
          <%= link_to owner_path(owner.id) do %>
              <%= owner.name %>
            <% end %>
          </td>
          <td>
            <%= link_to client_path(owner.client_id) do %>
              <%= owner.client.name %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto">
      <%= paginate @owners %>
    </div>
  </div>
</div>

app/views/owners/material_create.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2><%= @owner.name %>様資材追加</h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @owner, local: true do |f| %>
        <%= f.fields_for :materials do |m| %>
          <%= render 'material_fields', f: m %>
        <% end %>
          <div class="links">
            <%= link_to_add_association "追加", f, :materials, class: "btn btn-outline-secondary" %>
          </div>
          <div class="float-right">
            <%= f.submit "新規登録", class: "btn btn-outline-secondary" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/owners/material_edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2><%= @owner.name %>様発注内容編集</h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <%= form_with model: @owner, url: material_update_owner_path(@owner), local: true do |f| %>
        <%= f.fields_for :materials do |m| %>
        <div class="nested-fields">
          <%= render 'material_edit_fields', f: m, owner: @owner %>
        </div>
        <% end %>
        <div>
          <%= f.submit "更新", class: "btn btn-outline-secondary" %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/owners/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2>物件追加画面</h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @owner, local: true do |f| %>
      <%= f.fields_for :materials do |m| %>
      <div>
        <div class="form-group">
          <%= f.label :name, "物件名", class: "font-weight-bold" %>
          <%= f.text_field :name %>
        </div>
        <div class="row form-group">
          <div class="font-weight-bold ml-3">顧客名</div>
          <div class="ml-1">
            <%= f.collection_select(:client_id, @clients, :id, :name) %>
          </div>
          
        </div>
        <div class="form-group">
          <%= f.label :material_name, "資材名", class: "font-weight-bold" %>
          <%= render 'material_new_fields', f: m %>
          <div class="links">
            <%= link_to_add_association "追加", f, :materials, class: "btn btn-outline-secondary" %>
          </div>
        </div>
      </div>
      <div>
        <%= f.submit "新規登録", class: "btn btn-outline-secondary" %>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

</div>

app/views/owners/show.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2><%= @owner.name %>様</h2>
    </div>
    <div class="mt-3">
      <%= link_to "見積もり一覧へ", quotations_index_path(@owner), class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="mx-auto text-center">
    <table class="table table-bordered">
      <thead class="bg-light">
        <tr>
          <th>資材名</th>
          <th>発注状況</th>
          <th>発注予定日</th>
        </tr>
      </thead>
      <tbody>
        <% @materials.each do |material| %>
        <tr>
          <td>
            <%= material.material_name %>
          </td>
          <td>
            <% if material.order_status == false %>
              未発注
            <% else %>
              発注済み
            <% end %>
          </td>
          <td>
            <%= material.order_date %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-4">
      <%= link_to "物件情報編集", edit_owner_path(@owner), class: "btn btn-outline-secondary" %>
    </div>
    <div class="col-4">
      <%= link_to "発注内容変更", material_edit_owner_path(@owner), class: "btn btn-outline-secondary" %>
    </div>
    <div class="col-4">
      <%= link_to "資材追加", material_create_owner_path(@owner), method: :get, class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>