config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root "users/sessions#new"
  end
  #ログイン画面をトップ画面に

  devise_for :users, :controller => {
    sessions: 'users/sessions'
  }

  get '/top'=> 'tasks#index'

  resources :users ,only: [:index, :show, :edit, :update]
  resources :owners do
    collection do
      get 'search' => 'owners#search' #検索窓追加のため
    end
    member do
      get 'material_edit'
      get 'material_create'
      post 'material_create'
      patch 'material_update'
    end
  end

  resources :quotations
  get '/owner/:id/quotations/' => 'quotations#index', as: 'quotations_index'
  get '/owner/:id/quotations/new' => 'quotations#new', as: 'quotation_new'
  #物件の見積もり一覧取得のため

  resources :clients do
    collection do
      get 'search' => 'clients#search'
    end
  end
  #検索窓追加のため

  resources :chats
  resources :rooms, only: %i[create index show]
  resources :materials do
    collection do
      post 'update_all'
    end
  end

  resources :tasks

  get 'unsubscribe/:name' => 'users#unsubscribe', as: 'confirm_unsubscribe' #退会画面へ遷移
  patch '/users/:id/unsubscribe' => 'users#withdraw', as: 'unsubscribe_withdraw_user' #会員ステータス切り替え



end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :quotations
  has_many :clients
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :tasks, dependent: :destroy

  def active_for_authentication?
    super && self.is_deleted?
  end

  def inactive_message
    self.is_deleted? ? super : :special_condition_is_not_valid
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.active_for_authentication? == false
        flash[:error] = "退会済みです"
        redirect_to new_uer_session_path
      end
    else
      flash[:error] = "必要項目を入力してください"
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
      flash[:success] = "情報を更新しました"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = User.find(params[:id])
    if @user.update(is_deleted: false)
      sign_out current_user
    end
    redirect_to root_path
  end


  private
  def user_params
    params.require(:user).permit(:is_deleted, :name, :email, :director, :telephon_number, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <h2 class="mx-auto">マイページ編集画面</h2>
  </div>

  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @user do |f| %>
      <table class="mx-auto mb-1">
        <tr>
          <th>画像</th>
          <td>
            <%= f.attachment_field :profile_image %>
          </td>
        </tr>
        <tr>
          <th>氏名</th>
          <td>
            <%= f.text_field :name %>
          </td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td>
            <%= f.text_field :email %>
          </td>
        </tr>
        <tr>
          <th>役職名</th>
          <td>
            <%= f.text_field :director %>
          </td>
        </tr>
        <tr>
          <th>社用携帯番号</th>
          <td>
            <%= f.text_field :telephon_number %>
          </td>
        </tr>
      </table>
      <div class="text-center">
        <%= f.submit "変更", class: "btn btn-outline-secondary" %>
        <%= link_to "退会", confirm_unsubscribe_path(@user), class: "btn btn-danger" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="mx-auto">社員一覧</h2>
  </div>
</div>
<div class="container">
    <div class="mx-auto">
      <table class="table table-borderless text-center">
        <thead>
          <tr>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |f| %>
          <tr>
            <td>
              <%= link_to user_path(f.id) do %>
              <%= f.name %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <% if @user == current_user %>
      <h2 class="mx-auto">マイページ</h2>
    <% else %>
      <h2 class="mx-auto">ユーザー詳細ページ</h2>
    <% end %>
  </div>
  <div class="text-right">
    <% if @user == current_user %>
      <%= link_to "編集", edit_user_path(@user), class: "btn btn-outline-secondary" %>
    <% end %>
  </div>

  <div class="row">
    <div class="mx-auto">
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", format: 'jpeg' %>
    </div>
  </div>
  <div class="row">
    <table class="mx-auto mt-">
      <tr>
        <th class="">氏名</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>役職名</th>
        <td><%= @user.director %></td>
      </tr>
      <tr>
        <th>社用携帯番号</th>
        <td><%= @user.telephon_number %></td>
      </tr>
      <tr>
        <td>
          <% if current_user != @user %>
            <%= link_to 'チャット画面へ', rooms_path(user_id: @user), method: :post, class: "btn btn-outline-secondary" %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="text-right">
    <%= link_to "社員一覧", users_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container my-5">
  <div class="row">
    <div class="offset-3 col-6">
      <h3 class="text-center">本当に退会しますか？</h3>
    </div>
  </div>
  <div class="d-flex align-items-center justify-content-center" style="height:300px;">
    <div>
      <p align="center" style="color:red">※退会後、物件情報や発注状況が閲覧できなくなります</p>

      <div class="row my-5">
        <div class="offset-2">
          <%= link_to "キャンセル", user_path(current_user), class: "btn btn-outline-secondary" %>
        </div>
        <div class="offset-2">
          <%= link_to "退会する", unsubscribe_withdraw_user_path(@user),method: :patch, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>


<!--退会後もuserが保存したデータを残すため、退会フラグにする-->