config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root "users/sessions#new"
  end
  #ログイン画面をトップ画面に

  devise_for :users, :controller => {
    sessions: 'users/sessions'
  }

  get '/top'=> 'tasks#index'

  resources :users ,only: [:index, :show, :edit, :update]
  resources :owners do
    collection do
      get 'search' => 'owners#search' #検索窓追加のため
    end
    member do
      get 'material_edit'
      get 'material_create'
      post 'material_create'
      patch 'material_update'
    end
  end

  resources :quotations
  get '/owner/:id/quotations/' => 'quotations#index', as: 'quotations_index'
  get '/owner/:id/quotations/new' => 'quotations#new', as: 'quotation_new'
  #物件の見積もり一覧取得のため

  resources :clients do
    collection do
      get 'search' => 'clients#search'
    end
  end
  #検索窓追加のため

  resources :chats
  resources :rooms, only: %i[create index show]
  resources :materials do
    collection do
      post 'update_all'
    end
  end

  resources :tasks

  get 'unsubscribe/:name' => 'users#unsubscribe', as: 'confirm_unsubscribe' #退会画面へ遷移
  patch '/users/:id/unsubscribe' => 'users#withdraw', as: 'unsubscribe_withdraw_user' #会員ステータス切り替え



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room


end

app/models/client.rb
class Client < ApplicationRecord

    has_many :owners
    #has_many :sales_outlets
    #has_many :construction_shops
    belongs_to :user, optional: true

    def self.search(keyword)
        where(["name like?", "%#{keyword}%"])
    end
end

app/models/construction_shop.rb
class ConstructionShop < ApplicationRecord
  #belongs_to :client
  belongs_to :sales_outlet, optional: true
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :owner, inverse_of: :materials
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :quotations
  belongs_to :client

  has_many :materials, dependent: :destroy, inverse_of: :owner
  accepts_nested_attributes_for :materials, allow_destroy: true #ビューからデータを送る際にownerと一緒にmaterialを送る

  def self.search(keyword)
    where(["name like?", "%#{keyword}%"])
  end
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :owner
  belongs_to :user
  
  mount_uploader :pdf, AvatarUploader
  #has_many_attached :pdfs

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms, dependent: :destroy
  has_many :chats
  has_many :users, through: :user_rooms

  # チャット通知を既読にするためのメゾット
  def check_chats_notification(current_user)
    unchecked_chats = chats.includes(:user).where(checked: false).where.not(user_id: current_user.id)
 # &.を記述することで、uncheked_chatsがnilの場合エラーをNoMethodErrorを出さずにnilを返す。
    unchecked_chats&.each { |unchecked_chat| unchecked_chat.update(checked: true) }
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :quotations
  has_many :clients
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :tasks, dependent: :destroy

  def active_for_authentication?
    super && self.is_deleted?
  end

  def inactive_message
    self.is_deleted? ? super : :special_condition_is_not_valid
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
 before_action :authenticate_user!

 def index
  @users = User.all.page(params[:page]).per(10)
 end

 def show
  @user = User.find(params[:id])
  rooms = current_user.user_rooms.pluck(:room_id)
  user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

  if user_rooms.nil? #チャットroomがない場合新規作成
   @room = Room.new
   @room.save
   UserRoom.create(user_id: @user.id, room_id: @room.id) #チャット相手のroom作成
   UserRoom.create(user_id: current_user.id, room_id: @room.id) #カレントユーザーのroom作成
  else #チャットルームがすでにある場合の分岐
   @room = user_rooms.room
  end

  @chats = @room.chats
  @chat = Chat.new(room_id: @room.id)
 end

 def create
  @chat = current_user.chats.new(chat_params)
  @chat.save! #非同期通信のため、redirect先の記載なし
 end

 private

 def chat_params
  params.require(:chat).permit(:message, :room_id)
 end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  def new
    @client = Client.new
  end

  def index
    @clients = Client.all.page(params[:page]).per(10) #ページネーション
  end

  def show
    @client = Client.find(params[:id])
    @owners = @client.owners.page(params[:page]).per(10 )#ページネーション

  end

  def create
    @client = Client.new(client_params)
    if @client.save!
      redirect_to clients_path
    else
      redirect_back(fallback_location: root_path)
    end

  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:success] = "情報を更新しました"
       redirect_to client_path(@client)
    else
      render 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_path
  end

  def search
    @clients = Client.search(params[:keyword]).page(params[:page]).per(10) #検索結果の画面にもページネーション
    @keyword = params[:keyword]
    render "index" #検索窓
  end

  private
  def client_params
    params.require(:client).permit(:user_id, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2>顧客編集画面</h2>
    </div>
  </div>
</div>

<div class="container">
   <div class="text-center">
    <%= form_with model: @client, local: true do |f| %>
      <div class="mb-3">
        <%= f.label :name, "顧客名" %>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.submit "変更", class: "btn btn-outline-secondary" %>
        <%= link_to "削除", client_path(@client), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-outline-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/clients/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2>顧客一覧</h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="text-right">
    <%= form_with url: search_clients_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, value: @keyword %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="text-left mb-1">
    <%= link_to "顧客追加", new_client_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

<div class="container">
  <div class="mx-auto text-center">
    <table class="table table-bordered">
      <thead class="bg-light">
        <tr>
          <th>顧客名</th>
          <th>物件数</th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |f| %>
        <tr>
          <td>
            <%= link_to client_path(f.id) do %>
              <%= f.name %>
            <% end %>
          </td>
          <td>
            <%= f.owners.count %>件
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto text-secondary">
      <%= paginate @clients %>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2>顧客新規登録画面</h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto">
      <%= form_with model: @client, url: clients_path, local: true do |f| %>
      <table>
        <tr>
          <th>顧客名</th>
          <td>
            <%= f.text_field :name %>
            <%= f.hidden_field :user_id, value: current_user.id %>
          </td>
        </tr>
      </table>
      <div>
        <%= f.submit "新規登録", class: "btn btn-outline-secondary mt-3" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-3">
      <h2><%= @client.name %>様</h2>
    </div>
  </div>
</div>

<div class="container">

    <div class="text-right">
      <%= link_to "顧客編集", edit_client_path, class: "btn btn-outline-secondary" %>
    </div>

</div>

<div class="container">
  <div class="mx-auto text-center">
    <table class="table table-borderless">
      <thead>
        <tr>
          <th>物件一覧</th>
        </tr>
      </thead>
      <tbody>
        <% @owners.each do |owner| %>
        <tr>
          <td>
            <%= link_to owner_path(owner) do %>
            <%= owner.name %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="mx-auto">
      <%= paginate @owners %>
    </div>
  </div>
</div>