config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root "users/sessions#new"
  end
  #ログイン画面をトップ画面に

  devise_for :users, :controller => {
    sessions: 'users/sessions'
  }

  get '/top'=> 'tasks#index'

  resources :users ,only: [:index, :show, :edit, :update]
  resources :owners do
    collection do
      get 'search' => 'owners#search' #検索窓追加のため
    end
    member do
      get 'material_edit'
      get 'material_create'
      post 'material_create'
      patch 'material_update'
    end
  end

  resources :quotations
  get '/owner/:id/quotations/' => 'quotations#index', as: 'quotations_index'
  get '/owner/:id/quotations/new' => 'quotations#new', as: 'quotation_new'
  #物件の見積もり一覧取得のため

  resources :clients do
    collection do
      get 'search' => 'clients#search'
    end
  end
  #検索窓追加のため

  resources :chats
  resources :rooms, only: %i[create index show]
  resources :materials do
    collection do
      post 'update_all'
    end
  end

  resources :tasks

  get 'unsubscribe/:name' => 'users#unsubscribe', as: 'confirm_unsubscribe' #退会画面へ遷移
  patch '/users/:id/unsubscribe' => 'users#withdraw', as: 'unsubscribe_withdraw_user' #会員ステータス切り替え



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room


end

app/models/client.rb
class Client < ApplicationRecord

    has_many :owners
    #has_many :sales_outlets
    #has_many :construction_shops
    belongs_to :user, optional: true

    def self.search(keyword)
        where(["name like?", "%#{keyword}%"])
    end
end

app/models/construction_shop.rb
class ConstructionShop < ApplicationRecord
  #belongs_to :client
  belongs_to :sales_outlet, optional: true
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :owner, inverse_of: :materials
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :quotations
  belongs_to :client

  has_many :materials, dependent: :destroy, inverse_of: :owner
  accepts_nested_attributes_for :materials, allow_destroy: true #ビューからデータを送る際にownerと一緒にmaterialを送る

  def self.search(keyword)
    where(["name like?", "%#{keyword}%"])
  end
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :owner
  belongs_to :user
  
  mount_uploader :pdf, AvatarUploader
  #has_many_attached :pdfs

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms, dependent: :destroy
  has_many :chats
  has_many :users, through: :user_rooms

  # チャット通知を既読にするためのメゾット
  def check_chats_notification(current_user)
    unchecked_chats = chats.includes(:user).where(checked: false).where.not(user_id: current_user.id)
 # &.を記述することで、uncheked_chatsがnilの場合エラーをNoMethodErrorを出さずにnilを返す。
    unchecked_chats&.each { |unchecked_chat| unchecked_chat.update(checked: true) }
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :quotations
  has_many :clients
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :tasks, dependent: :destroy

  def active_for_authentication?
    super && self.is_deleted?
  end

  def inactive_message
    self.is_deleted? ? super : :special_condition_is_not_valid
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bukkenkun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/*******.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダー部-->
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <div class="text-middle">
            <% if user_signed_in? %>
              <%= current_user.name %>さんお疲れ様です
            <% end %>

          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item mr-3"><%= link_to "ホーム", root_path, class: 'btn btn-outline-secondary' %></li>
                <li class="nav-item mr-3"><%= link_to "マイページ", user_path(current_user), class: 'btn btn-outline-secondary' %></li>
                <li class="nav-item mr-3">
                  <%= link_to chats_path, class: 'btn btn-outline-secondary' do %>
                    <%= "チャット" %>
                    <%# if current_user.unchecked_chats? %>
                      <!--<i class="fa fa-circle fa-xs n-circle-chat" style="color: blue"></i>-->
                    <%# end %>
                  <% end %>
                </li>
                <li class="nav-item mr-3"><%= link_to "顧客", clients_path, class: 'btn btn-outline-secondary' %></li>
                <li class="nav-item mr-3"><%= link_to "物件", owners_path, class: 'btn btn-outline-secondary' %></li>
                <li class="nav-item mr-3"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <!--ボディー部-->
    <%= yield %>
  </body>
</html>